# Generated by Django 2.2.6 on 2020-04-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('Id_Ciudad', models.IntegerField(db_column='Id_Ciudad', primary_key=True, serialize=False)),
                ('Nombre_C', models.CharField(blank=True, db_column='Nomb_C', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('Id_Cliente', models.IntegerField(db_column='Id_Cliente', primary_key=True, serialize=False)),
                ('NombreC', models.CharField(blank=True, db_column='NombC', max_length=30, null=True)),
                ('AP_C', models.CharField(blank=True, db_column='AP_C', max_length=30, null=True)),
                ('AM_M', models.CharField(blank=True, db_column='AM_M', max_length=30, null=True)),
                ('TCel_C', models.IntegerField(blank=True, db_column='TCel_C', null=True)),
                ('TCasa_C', models.IntegerField(blank=True, db_column='TCasa_C', null=True)),
                ('Cantidad_Personas', models.IntegerField(blank=True, db_column='Cantidad de personas', null=True)),
                ('Ciudad', models.CharField(blank=True, db_column='Ciudad', max_length=15, null=True)),
                ('Estado', models.CharField(blank=True, db_column='Estado', max_length=15, null=True)),
                ('Pais', models.CharField(blank=True, db_column='Pais', max_length=15, null=True)),
                ('Numero_Habitaciones', models.IntegerField(blank=True, db_column='Numero_Habitaciones', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('Id_Estado', models.IntegerField(db_column='Id_Ciudad', primary_key=True, serialize=False)),
                ('Nombre_C', models.CharField(blank=True, db_column='Nomb_C', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('Numero_Habitaciones', models.IntegerField(db_column='Id_Cliente', primary_key=True, serialize=False)),
                ('Precio', models.FloatField(blank=True, db_column='NombC', null=True)),
                ('Disponibilidad', models.BooleanField(blank=True, db_column='AP_C', null=True)),
                ('Tipo', models.CharField(blank=True, db_column='AM_M', max_length=30, null=True)),
                ('Descripcion', models.CharField(blank=True, db_column='Sexo', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('Id_Pais', models.IntegerField(db_column='Id_Ciudad', primary_key=True, serialize=False)),
                ('Nombre_P', models.CharField(blank=True, db_column='Nomb_C', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recepcionistas',
            fields=[
                ('Id_Empleado', models.IntegerField(db_column='Id_Empleado', primary_key=True, serialize=False)),
                ('Nombre_R', models.CharField(blank=True, db_column='Nombre_R', max_length=30, null=True)),
                ('AP_R', models.CharField(blank=True, db_column='AP_C', max_length=30, null=True)),
                ('AM_R', models.CharField(blank=True, db_column='AM_M', max_length=30, null=True)),
                ('Turno', models.CharField(blank=True, db_column='Sexo', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservaciones',
            fields=[
                ('Id_Reservacion', models.IntegerField(db_column='Id_Reservacion', primary_key=True, serialize=False)),
                ('Fecha_Reservacion', models.DateField(blank=True, db_column='Fecha_Reservacion', null=True)),
                ('Fecha_Entrada', models.DateField(blank=True, db_column='Fecha_Entrada', null=True)),
                ('Fecha_Salida', models.DateField(blank=True, db_column='Fecha_Salida', null=True)),
                ('Total', models.FloatField(blank=True, db_column='Total', null=True)),
                ('Subtotal', models.FloatField(blank=True, db_column='Subtotal', null=True)),
            ],
        ),
    ]
